### ISSUE TITLE
Создать классы игрок и корабль

### ISSUE THREAD

**Issue by Kortvk** [ZhdanovPasha/SpaceInvaders#15]

**Comment by BlackRule** [comment]
PS: Посмотрите как написал код Николай в resources.js sprite.js и тд Вот так надо организовывать код на JS. Каждый файл содержит тут-же исполняющуюся ф-ю. Переменные в ней ЛОКАЛЬНЫЕ. Если она хочет изменить внешний мир изменяет его через window (у Николая) либо (еще лучше) принимает параметр к себе game допустим из внешнего мира и внутри себя его изменяет (то же что если бы изменять window.game....)

**Comment by ZhdanovPasha** [comment]
Осталось доделать класс Blue
