### ISSUE TITLE
Придумать скилы

### ISSUE THREAD

**Issue by ZhdanovPasha** [ZhdanovPasha/SpaceInvaders#3]

**Comment by BlackRule** [comment]
Будет сделан скилл Laser у Blue

**Comment by ZhdanovPasha** [comment]
На данный момент сделаны скилы у розовых: скорострельность, ускорение и неуязвимость

**Comment by ZhdanovPasha** [comment]
Доделаны скилы
У голубых  скил призыв нескольких ботов
